apiVersion: v1
kind: LimitRange
metadata:
  name: dev-limits
  namespace: ns-dev
spec:
  limits:
  - max:
      cpu: "0.2"
      memory: 256Mi
    default:
      cpu: "0.2"
      memory: 256Mi
    defaultRequest:
      cpu: "0.1"
      memory: 128Mi
    type: Container
