apiVersion: apps/v1
kind: Deployment
metadata:
  name: zero-test
  namespace: ns-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zero-test
  template:
    metadata:
      labels:
        app: zero-test
    spec:
      containers:
      - name: nginx
        image: nginx
